<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>69ce1f91-a836-4bc4-9e24-1a2b65c3dd72</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FornoPizza.Data\FornoPizza.Data.csproj" />
  </ItemGroup>

</Project>
